# Site settings
title: Hosein Fooladi blog
email: 
description: "Ssytem Biology and Deep Learning Researcher"
baseurl: ""
url: "http://hfooladi.github.io"
twitter_username: HoseinFooladi7
github_username:  HFooladi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
